# Generated by Django 4.2.7 on 2025-05-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_quality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('frame_rate', models.IntegerField(default=30)),
                ('record_audio', models.BooleanField(default=True)),
                ('audio_source', models.CharField(choices=[('mic', 'Microphone'), ('system', 'System Audio'), ('both', 'Both'), ('none', 'None')], default='mic', max_length=10)),
                ('show_cursor', models.BooleanField(default=True)),
                ('countdown_seconds', models.IntegerField(default=3)),
                ('auto_save', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recorder_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
